[WEB-34861] Fix IPv6 Validation
tophatmonocle/pysaml2 pull request #4
Opened 2021-01-20 19:38 UTC by wenyu-gu

This is to fix a bug of not being able to validate the IPv6 address with square brackets around it. Please refer to the original [issue](https://github.com/IdentityPython/pysaml2/issues/627) and [fix](https://github.com/IdentityPython/pysaml2/pull/653).

Ticket:
https://tophat.atlassian.net/browse/WEB-34861

### All Submissions:

* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [ ] Have you added an explanation of what problem you are trying to solve with this PR?
* [ ] Have you added information on what your changes do and why you chose this as your solution?
* [ ] Have you written new tests for your changes?
* [ ] Does your submission pass tests?
* [ ] This project follows PEP8 style guide. Have you run your code against the 'flake8' linter?

2021-01-20 22:12 UTC, toboklee requested changes
Based on our discussion, I figured out a way to run the test.

You can run the tests by installing `test-requirements.py` (from README.md instructions)
and also, i had to manually install current package by doing `pip install -e .` (from the root DIR)

anddddddd
a minor, but critical typo :)

2021-01-20 22:12 UTC, toboklee commented on src/saml2_tophat/validate.py
> +    is_enclosed_in_brackets = address.startwith("[") and address.endswith("]")
```suggestion
    is_enclosed_in_brackets = address.startswith("[") and address.endswith("]")
```

2021-01-20 22:33 UTC, wenyu-gu commented on src/saml2_tophat/validate.py
> +    is_enclosed_in_brackets = address.startwith("[") and address.endswith("]")
Good catch! Just pushed changes.

2021-01-20 23:25 UTC, toboklee approved these changes
LGTM!

2021-01-21 17:28 UTC, linusrachlis approved these changes
QA by installing the wheel in local THM and successfully passing SSO flow ✅

2021-01-21 17:30 UTC, merged